### ISSUE TITLE
Addition of the "Lap"Function

### ISSUE THREAD

**Issue by JoshuaPadayao** [JoshuaPadayao/Moontong-Underpaid-Devs#1]
The source code lacks the "lap" feature. The task is to **add a code that will let users press a button and then save the intended interval they want to record**. The preview of saved laps must be strategically placed somewhere in the GUI.

**Comment by JohnNicole2001** [comment]
I added a new code to compare our source code to this new one so that we can improve our output the new code has a lap function.

**Comment by JoshuaPadayao** [comment]
Thank you!

**Comment by JoshuaPadayao** [comment]
I uploaded a new source code in my branch and added various features including "lap" and the preview of saved laps.
