### ISSUE TITLE
Solve the problem for the compare code

### ISSUE THREAD

**Issue by JohnNicole2001** [JoshuaPadayao/Moontong-Underpaid-Devs#10]
Hello guys I've been stuck in this for a while when ever the minute passes it always add 2 not 1 I don't know if it also applies with the hour time.

**Comment by JoshuaPadayao** [comment]
I'm working on it.

**Comment by JoshuaPadayao** [comment]
I made changes to the source code that fixed this issue. I will pull it soon.
