### ISSUE TITLE
Change-Theme Function

### ISSUE THREAD

**Issue by JoshuaPadayao** [JoshuaPadayao/Moontong-Underpaid-Devs#7]
Incorporate a code that will let users change the stopwatch's (background) color display.

**Comment by Shaceline26** [comment]
done with the basic backbone of this theme

**Comment by Shaceline26** [comment]
I suggest that the icons also will change that accords to the theme

**Comment by JoshuaPadayao** [comment]
> I suggest that the icons also will change that accords to the theme
> 

I agree. That would look better.

**Comment by JoshuaPadayao** [comment]
Ongoing feature
