### ISSUE TITLE
Sound Feature

### ISSUE THREAD

**Issue by JoshuaPadayao** [JoshuaPadayao/Moontong-Underpaid-Devs#8]
1. Add a code that would **play a sound** (preferably short; _.wav_ format) when a certain button is pressed (not necessarily all buttons).
2. Add a code that would give users the **ability to turn off this feature**.
3. _(Optional)_ Add a code that would let users **choose and change the sound** from the program's own library.

**Comment by AnneCornelia** [comment]
On it! ✊

**Comment by RizzaMollaneda** [comment]
Me too!
